[tool.git_changelog]
provider = "github"
repository = "um-computacion/computacion-2025-backgammon-felialiaga"
convention = "angular"
template = "keepachangelog"
sections = [
  { title = "Features",  grep = "feat" },
  { title = "Fixes",     grep = "fix" },
  { title = "Others",    grep = ".*" }
]
